### ISSUE TITLE
[Feature] Support ESLint v9

### ISSUE THREAD

**Issue by theoludwig** [theoludwig/eslint-config-conventions#2]
Reference: https://eslint.org/blog/2024/04/eslint-v9.0.0-released/

**Comment by walidkorchi** [comment]
This might be handy for you as I had stumbled upon your config:
> Also this comment is subject to change

- `no-new-symbol` deprecated and replaced by [no-new-native-nonconstructor](https://eslint.org/docs/latest/rules/no-new-native-nonconstructor)
- `no-confusing-arrow` deprecated in ESLint v8.53.0
- `no-mixed-operators` deprecated in ESLint v8.53.0
- `quote-props` deprecated in ESLint v8.53.0

> *Out of context of this issue, we might want to remove `{ "allowKeywords": true }` for `dot-notation` because by default it is set to true*, same for `enforceForSwitchCase` option key inside `use-isnan`, `newIsCap` option key inside `new-cap`, `allowSamePrecedence` option key inside `no-mixed-operators`

> *Again out of context, we might want to add `enforceForJSX` to true in `no-unused-expressions`*

**Comment by theoludwig** [comment]
Related issues:
- ~~https://github.com/import-js/eslint-plugin-import/issues/2948~~
- https://github.com/eslint-community/eslint-plugin-promise/issues/449
- https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2250
- https://github.com/typescript-eslint/typescript-eslint/issues/8211
- https://github.com/eslint/eslint/issues/18391
- https://github.com/vercel/next.js/issues/64409

**Comment by walidkorchi** [comment]
Yesterday, I started migrating from v8.5.6 to v9.2.0 in another project, and it was a burden because of how much the Eslint's server, I guess, is no synced with the VSCode extension's version. I had to install the pre-release version, and yet I ran onto issues where `.eslintrc` files couldn't be found because Eslint has switched to flat configs: `eslint.config.js`, and this is where I realized that this wouldn't be possible, at least for for now, because a lot of plugins that currently use do not support the latest version of Eslint.
I think we just have to wait for merge PRs.
